language: php

sudo: false

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - composer self-update
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
